Adding install for package and renaming project
JCSDA-internal/ioda-data pull request #175
Opened 2023-10-19 20:43 UTC by fabiolrdiniz

## Description
This PR is adding the install procedures for this repo to behave like a package, allowing one to rely on the `ioda-data_FOUND` variable in a bundle. It's also renaming the project to be consistent with its repo name (with a dash instead of an underscore).

Note: unfortunately, the ecbuild-based option for it is being added here, due to my lack of knowledge of the minimal lines to be added without that dependency --- I believe its removal can be done later when removing all the ecbuild dependencies across the repos.

## Issue(s) addressed
TO-BE-CREATED

## Dependencies
None.

## Impact

Expected impact on downstream repositories:

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have run the unit tests before creating the PR

2023-10-20 16:04 UTC, srherbener requested changes

2023-10-20 16:04 UTC, srherbener commented on CMakeLists.txt
> +project( ioda-data VERSION 2.7.0 DESCRIPTION "IODA Test Files" )
I think we should not use the hyphen "-" in the project name. The reason is that you cannot use a hyphen in a shell environment variable name. Ie the recommendation about setting "ioda-data_DIR" variable is not possible to do:
```
CMake Error at ioda/CMakeLists.txt:76 (find_package):
  By not providing "Findioda-data.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ioda-data", but CMake did not find one.

  Could not find a package configuration file provided by "ioda-data" with
  any of the following names:

    ioda-dataConfig.cmake
    ioda-data-config.cmake

  Add the installation prefix of "ioda-data" to CMAKE_PREFIX_PATH or set
  "ioda-data_DIR" to a directory containing one of the above files.  If
  "ioda-data" provides a separate development package or SDK, be sure it has
  been installed.
```

2023-12-01 18:31 UTC, fabiolrdiniz commented
Please, do not merge this until we decide on how to proceed. Changing it to be a draft.

2023-12-18 22:59 UTC, srherbener commented
@fabiolrdiniz should we temporarily close this one too (since you closed https://github.com/JCSDA-internal/ioda/pull/1140)? Thanks!

2023-12-18 23:40 UTC, fabiolrdiniz commented
@srherbener, sure!

2023-12-18 23:40 UTC, closed without merging

2023-12-19 17:52 UTC, srherbener commented
Thanks @fabiolrdiniz!